### ISSUE TITLE
NodeTypes rule suggestion

### ISSUE THREAD

**Issue by freund0** [sitegeist/Sitegeist.Neos.BestPractices#6]
1. NodeTypes SHOULD use reasonable groups, icons and labels to distinguish the elements from each other (e.g. structural vs content elements). Content elements that are allowed to exist in the tree but should not be available to the user MUST NOT be visible. This MAY be achieved via constraint (RECOMMENDED), policy, non-existent groups or by declaring legacy-nodetypes abstract.

2. It is RECOMMENDED to use a dedicated NodeType for the site-node. This allows to add site-settings to the inspector, control the rendering and define important documents as autocreated childnodes.

**Comment by mficzel** [comment]
All merged
